version: "1"

services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: s339795
      POSTGRES_PASSWORD: FH91Ze1WDQJk6Oed
    ports:
      - "5432:5432"

  camunda:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - "8080:8080"

  mainMicroservice:
    image: main-microservice
    ports:
      - "8082:8082"

  mediaMicroservice:
    image: media-microservice
    ports:
      - "8081:8081"