spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://pg:5432/studs}
    username: ${DB_USERNAME:s339795}
    password: ${DB_PASSWORD:FH91Ze1WDQJk6Oed}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: ${MAIN_MICROSERVICE_PORT:8082}

JWT_SECRET_KEY: ${JWT_SECRET:6A576E5A7234753778214125442A472D4B6150645267556B703273357638792F}

SUBSCRIPTION_PRICE: ${SUB_PRICE:200}

RABBITMQ_HOST: ${RABBIT_HOST:tcp://5.23.55.30:1883}
CAMUNDA_URL: ${CAMUNDA_PATH:http://camunda:8080/engine-rest}
